<?php

return [
    'modules' => [
        'dashboard' => [
            'label' => 'Dashboard',
            'subject' => 'dashboard',
            'abilities' => ['view'],
        ],
        'user_management' => [
            'label' => 'User Management',
            'subject' => 'user management',
            'abilities' => ['view', 'create', 'edit', 'delete'],
        ],
        'role_permission' => [
            'label' => 'Role & Permission',
            'subject' => 'role permission',
            'abilities' => ['view', 'create', 'edit', 'delete'],
        ],
        'clinic_settings' => [
            'label' => 'Clinic Settings',
            'subject' => 'clinic settings',
            'abilities' => ['view', 'edit'],
        ],
        'branch_settings' => [
            'label' => 'Branch Settings',
            'subject' => 'branch settings',
            'abilities' => ['view', 'create', 'edit', 'delete'],
        ],
        'counter_management' => [
            'label' => 'Counter Management',
            'subject' => 'counter management',
            'abilities' => ['view', 'create', 'edit', 'delete'],
        ],
        'section_management' => [
            'label' => 'Section Management',
            'subject' => 'section management',
            'abilities' => ['view', 'create', 'edit', 'delete'],
        ],
        'doctor_management' => [
            'label' => 'Doctor Management',
            'subject' => 'doctor management',
            'abilities' => ['view', 'create', 'edit', 'delete'],
        ],
        'doctor_schedule_management' => [
            'label' => 'Doctor Schedule',
            'subject' => 'doctor schedule',
            'abilities' => ['view', 'create', 'edit', 'delete'],
        ],
        'patient_management' => [
            'label' => 'Patient Management',
            'subject' => 'patient management',
            'abilities' => ['view', 'create', 'edit', 'delete'],
        ],
        'visit_registration_management' => [
            'label' => 'Visit Registration',
            'subject' => 'visit registration',
            'abilities' => ['view', 'create', 'edit', 'delete'],
        ],
        'queue_management' => [
            'label' => 'Queue Management',
            'subject' => 'queue management',
            'abilities' => ['view', 'create', 'edit', 'delete'],
        ],
        'vital_sign_management' => [
            'label' => 'Vital Sign Management',
            'subject' => 'vital sign management',
            'abilities' => ['view', 'create', 'edit', 'delete'],
        ],
        'medical_record_management' => [
            'label' => 'Medical Record Management',
            'subject' => 'medical record management',
            'abilities' => ['view', 'create', 'edit', 'delete'],
        ],
        'pharmacy_management' => [
            'label' => 'Pharmacy',
            'subject' => 'pharmacy management',
            'abilities' => ['view', 'create', 'edit', 'delete'],
        ],
        'prescription_management' => [
            'label' => 'Prescription',
            'subject' => 'prescription management',
            'abilities' => ['view', 'create', 'edit', 'delete'],
        ],
        'procedure_management' => [
            'label' => 'Procedure Management',
            'subject' => 'procedure management',
            'abilities' => ['view', 'create', 'edit', 'delete'],
        ],
        'medical_service_management' => [
            'label' => 'Medical Service Management',
            'subject' => 'medical service management',
            'abilities' => ['view', 'create', 'edit', 'delete'],
        ],
        'laboratory_management' => [
            'label' => 'Laboratory',
            'subject' => 'laboratory management',
            'abilities' => ['view', 'create', 'edit', 'delete'],
        ],
        'billing_management' => [
            'label' => 'Billing',
            'subject' => 'billing management',
            'abilities' => ['view', 'create', 'edit', 'delete'],
        ],
        'payment_method_management' => [
            'label' => 'Payment Methods',
            'subject' => 'payment method management',
            'abilities' => ['view', 'create', 'edit', 'delete'],
        ],
        'cashier_shift_management' => [
            'label' => 'Cashier Shifts',
            'subject' => 'cashier shift management',
            'abilities' => ['view', 'create', 'edit', 'delete'],
        ],
        'sales_invoice_management' => [
            'label' => 'Sales Invoices',
            'subject' => 'sales invoice management',
            'abilities' => ['view', 'create', 'edit', 'delete'],
        ],
        'receivable_management' => [
            'label' => 'Receivables',
            'subject' => 'receivable management',
            'abilities' => ['view', 'create', 'edit', 'delete'],
        ],
        'product_category_management' => [
            'label' => 'Product Categories',
            'subject' => 'product category management',
            'abilities' => ['view', 'create', 'edit', 'delete'],
        ],
        'supplier_management' => [
            'label' => 'Suppliers',
            'subject' => 'supplier management',
            'abilities' => ['view', 'create', 'edit', 'delete'],
        ],
        'purchase_order_management' => [
            'label' => 'Purchase Orders',
            'subject' => 'purchase order management',
            'abilities' => ['view', 'create', 'edit', 'delete', 'approve'],
        ],
        'goods_receipt_management' => [
            'label' => 'Goods Receipts',
            'subject' => 'goods receipt management',
            'abilities' => ['view', 'create', 'edit', 'delete'],
        ],
        'purchase_return_management' => [
            'label' => 'Purchase Returns',
            'subject' => 'purchase return management',
            'abilities' => ['view', 'create', 'edit', 'delete'],
        ],
        'stock_adjustment_management' => [
            'label' => 'Stock Adjustments',
            'subject' => 'stock adjustment management',
            'abilities' => ['view', 'create', 'edit', 'delete'],
        ],
        'stock_opname_management' => [
            'label' => 'Stock Opnames',
            'subject' => 'stock opname management',
            'abilities' => ['view', 'create', 'edit', 'delete'],
        ],
        'expiry_monitoring_management' => [
            'label' => 'Expiry Monitoring',
            'subject' => 'expiry monitoring management',
            'abilities' => ['view', 'edit'],
        ],
        'audit_log_management' => [
            'label' => 'Audit Logs',
            'subject' => 'audit log management',
            'abilities' => ['view'],
        ],
        'icd10_management' => [
            'label' => 'ICD-10 Management',
            'subject' => 'icd10 management',
            'abilities' => ['view', 'create', 'edit', 'delete'],
        ],
        'menu_management' => [
            'label' => 'Menu Management',
            'subject' => 'menu management',
            'abilities' => ['view', 'create', 'edit', 'delete'],
        ],
        'report_management' => [
            'label' => 'Reports',
            'subject' => 'report management',
            'abilities' => ['view'],
        ],
        'backup_management' => [
            'label' => 'Backup Center',
            'subject' => 'backup management',
            'abilities' => ['view', 'create', 'restore', 'delete'],
        ],
        'referral_management' => [
            'label' => 'Referral Management',
            'subject' => 'referral management',
            'abilities' => ['view', 'create', 'edit', 'delete', 'issue', 'print'],
        ],
        'doctor_letter_management' => [
            'label' => 'Doctor Letters',
            'subject' => 'doctor letter management',
            'abilities' => ['view', 'create', 'edit', 'delete', 'issue', 'print'],
        ],
        'reorder_point_management' => [
            'label' => 'Reorder Points',
            'subject' => 'reorder point management',
            'abilities' => ['view', 'create', 'edit', 'delete'],
        ],
        'drug_interaction_management' => [
            'label' => 'Drug Interactions',
            'subject' => 'drug interaction management',
            'abilities' => ['view', 'create', 'edit', 'delete'],
        ],
    ],

    'roles' => [
        'super-admin' => [
            'label' => 'Super Admin',
            'permissions' => '*',
        ],
        'clinic-admin' => [
            'label' => 'Clinic Admin',
            'permissions' => [
                'view dashboard',
                'view user management',
                'create user management',
                'edit user management',
                'view role permission',
                'edit role permission',
                'view clinic settings',
                'edit clinic settings',
                'view branch settings',
                'create branch settings',
                'edit branch settings',
                'delete branch settings',
                'view counter management',
                'create counter management',
                'edit counter management',
                'delete counter management',
                'view section management',
                'create section management',
                'edit section management',
                'delete section management',
                'view doctor management',
                'create doctor management',
                'edit doctor management',
                'delete doctor management',
                'view doctor schedule',
                'create doctor schedule',
                'edit doctor schedule',
                'delete doctor schedule',
                'view patient management',
                'create patient management',
                'edit patient management',
                'delete patient management',
                'view visit registration',
                'create visit registration',
                'edit visit registration',
                'delete visit registration',
                'view queue management',
                'create queue management',
                'edit queue management',
                'delete queue management',
                'view vital sign management',
                'create vital sign management',
                'edit vital sign management',
                'delete vital sign management',
                'view medical record management',
                'create medical record management',
                'edit medical record management',
                'delete medical record management',
                'view pharmacy management',
                'create pharmacy management',
                'edit pharmacy management',
                'delete pharmacy management',
                'view prescription management',
                'create prescription management',
                'edit prescription management',
                'delete prescription management',
                'view procedure management',
                'create procedure management',
                'edit procedure management',
                'delete procedure management',
                'view medical service management',
                'create medical service management',
                'edit medical service management',
                'delete medical service management',
                'view laboratory management',
                'create laboratory management',
                'edit laboratory management',
                'delete laboratory management',
                'view billing management',
                'create billing management',
                'edit billing management',
                'delete billing management',
                'view payment method management',
                'create payment method management',
                'edit payment method management',
                'delete payment method management',
                'view cashier shift management',
                'create cashier shift management',
                'edit cashier shift management',
                'delete cashier shift management',
                'view sales invoice management',
                'create sales invoice management',
                'edit sales invoice management',
                'delete sales invoice management',
                'view receivable management',
                'create receivable management',
                'edit receivable management',
                'delete receivable management',
                'view product category management',
                'create product category management',
                'edit product category management',
                'delete product category management',
                'view supplier management',
                'create supplier management',
                'edit supplier management',
                'delete supplier management',
                'view purchase order management',
                'create purchase order management',
                'edit purchase order management',
                'delete purchase order management',
                'approve purchase order management',
                'view goods receipt management',
                'create goods receipt management',
                'edit goods receipt management',
                'delete goods receipt management',
                'view purchase return management',
                'create purchase return management',
                'edit purchase return management',
                'delete purchase return management',
                'view stock adjustment management',
                'create stock adjustment management',
                'edit stock adjustment management',
                'delete stock adjustment management',
                'view stock opname management',
                'create stock opname management',
                'edit stock opname management',
                'delete stock opname management',
                'view expiry monitoring management',
                'edit expiry monitoring management',
                'view audit log management',
                'view report management',
                'view referral management',
                'create referral management',
                'edit referral management',
                'delete referral management',
                'issue referral management',
                'print referral management',
                'view doctor letter management',
                'create doctor letter management',
                'edit doctor letter management',
                'delete doctor letter management',
                'issue doctor letter management',
                'print doctor letter management',
                'view reorder point management',
                'create reorder point management',
                'edit reorder point management',
                'delete reorder point management',
                'view drug interaction management',
                'create drug interaction management',
                'edit drug interaction management',
                'delete drug interaction management',
                'view icd10 management',
                'create icd10 management',
                'edit icd10 management',
                'delete icd10 management',
                'view menu management',
                'create menu management',
                'edit menu management',
                'delete menu management',
            ],
        ],
        'front-office' => [
            'label' => 'Front Office',
            'permissions' => [
                'view dashboard',
                'view patient management',
                'create patient management',
                'edit patient management',
                'view visit registration',
                'create visit registration',
                'edit visit registration',
                'delete visit registration',
                'view queue management',
                'edit queue management',
                'view vital sign management',
                'create vital sign management',
                'edit vital sign management',
                'view billing management',
                'edit billing management',
                'view cashier shift management',
                'create cashier shift management',
                'edit cashier shift management',
                'view sales invoice management',
                'edit sales invoice management',
                'view receivable management',
                'create receivable management',
                'edit receivable management',
                'view referral management',
                'create referral management',
                'edit referral management',
                'issue referral management',
                'print referral management',
                'view doctor letter management',
                'create doctor letter management',
                'edit doctor letter management',
                'issue doctor letter management',
                'print doctor letter management',
            ],
        ],
        'doctor' => [
            'label' => 'Doctor',
            'permissions' => [
                'view dashboard',
                'view queue management',
                'view medical record management',
                'create medical record management',
                'edit medical record management',
                'view prescription management',
                'create prescription management',
                'edit prescription management',
                'view procedure management',
                'create procedure management',
                'edit procedure management',
                'view laboratory management',
                'create laboratory management',
                'edit laboratory management',
                'view referral management',
                'create referral management',
                'edit referral management',
                'issue referral management',
                'print referral management',
                'view doctor letter management',
                'create doctor letter management',
                'edit doctor letter management',
                'issue doctor letter management',
                'print doctor letter management',
                'view icd10 management',
            ],
        ],
        'nurse' => [
            'label' => 'Nurse',
            'permissions' => [
                'view dashboard',
                'view queue management',
                'view vital sign management',
                'create vital sign management',
                'edit vital sign management',
                'view procedure management',
                'create procedure management',
                'edit procedure management',
                'view laboratory management',
                'create laboratory management',
                'edit laboratory management',
                'view icd10 management',
            ],
        ],
        'cashier' => [
            'label' => 'Cashier',
            'permissions' => [
                'view dashboard',
                'view patient management',
                'create patient management',
                'edit patient management',
                'view visit registration',
                'create visit registration',
                'edit visit registration',
                'delete visit registration',
                'view queue management',
                'edit queue management',
                'view billing management',
                'edit billing management',
                'view cashier shift management',
                'create cashier shift management',
                'edit cashier shift management',
                'view sales invoice management',
                'edit sales invoice management',
                'view receivable management',
                'create receivable management',
                'edit receivable management',
            ],
        ],
        'pharmacist' => [
            'label' => 'Pharmacist',
            'permissions' => [
                'view dashboard',
                'view pharmacy management',
                'create pharmacy management',
                'edit pharmacy management',
                'delete pharmacy management',
                'view product category management',
                'create product category management',
                'edit product category management',
                'delete product category management',
                'view supplier management',
                'create supplier management',
                'edit supplier management',
                'delete supplier management',
                'view reorder point management',
                'create reorder point management',
                'edit reorder point management',
                'delete reorder point management',
                'view drug interaction management',
                'create drug interaction management',
                'edit drug interaction management',
                'delete drug interaction management',
                'view purchase order management',
                'create purchase order management',
                'edit purchase order management',
                'delete purchase order management',
                'view goods receipt management',
                'create goods receipt management',
                'edit goods receipt management',
                'delete goods receipt management',
                'view purchase return management',
                'create purchase return management',
                'edit purchase return management',
                'delete purchase return management',
                'view stock adjustment management',
                'create stock adjustment management',
                'edit stock adjustment management',
                'delete stock adjustment management',
                'view stock opname management',
                'create stock opname management',
                'edit stock opname management',
                'delete stock opname management',
                'view expiry monitoring management',
                'edit expiry monitoring management',
                'view prescription management',
                'create prescription management',
                'edit prescription management',
                'view billing management',
            ],
        ],
    ],
];
